### ISSUE TITLE
Enable or document shared formats

### ISSUE THREAD

**Issue by nathanl** [redwirelabs/speck#10]
The docs show using formats like this:

```elixir
attribute :uuid, :string,  format: ~r/\A\d{5}\-\d{5}\-\d{5}\-\d{5}\-\d{5}\z/
```

When multiple schemas use a uuid of that format, it would be less error-prone to be able to do something like:

```elixir
attribute :uuid, :string,  format: Formats.uuid()
```

I don't see anything like this in the docs. Is it supported? If not, could it be?

So far I've attempted to use a separate module and ensure that it's compiled before the schema using `require`, `@before_compile`, and `elixirc_paths`, but I always get an error saying that the module is unavailable. Maybe this is because the Speck compiler runs before any of the `Mix.compilers`?

**Comment by amclain** [comment]
>I don't see anything like this in the docs. Is it supported? If not, could it be?

We plan to support this is with custom attribute types, which is a feature in the backlog. I've documented it in this repo as issue #11.

A workaround to do what you wrote is to use [Code.require_file](https://hexdocs.pm/elixir/Code.html#require_file/2) in your spec:
```ex
Code.require_file "../lib/format.ex"

struct Example.Message

attribute :uuid, :string, format: Format.uuid
```
```ex
defmodule Format do
  def uuid do
    ~r/\A\d{5}\-\d{5}\-\d{5}\-\d{5}\-\d{4}\z/
  end
end
```

Please continue this thread if you run into any other issues with this approach.

**Comment by amclain** [comment]
Functionality will be covered by #11

**Comment by nathanl** [comment]
`Code.require_file "../lib/format.ex"` does not work because the Speck compiler ignores it [here](https://github.com/redwirelabs/speck/blob/efcf4ac09a81e0d0c6dd8c3e123bfd69300373e2/lib/mix/tasks/compiler.ex#L133).

**Comment by amclain** [comment]
Another workaround is to make the `Format` module a dependent library. It could be as simple as a path dependency in the same repo. That will cause the `Format` module to be compiled first, then Speck protocols, then the application code. This route also doesn't require adding any code to the header of the specs.
