### ISSUE TITLE
Strict validation

### ISSUE THREAD

**Issue by amclain** [redwirelabs/speck#8]
Normally coercion happens first, then validation. Add a `strict` property that performs validation before coercion.

`strict` can be applied to individual attributes:
```ex
struct MQTT.AddDevice.V1

name "add_device"

attribute :name, :string, strict: true
```

`strict` can be applied globally. When strict is `true` globally, individual attributes can be opted out with `strict: false`.
```ex
struct MQTT.AddDevice.V1

name "add_device"

strict true

attribute :name,    :string
attribute :address, :string, strict: false
```

**Comment by abelino** [comment]
Added in #9.
